version: '3.8'
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: heracare
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports: ["5432:5432"]
    volumes: ["pg_data:/var/lib/postgresql/data"]

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on: [zookeeper]
    ports: ["9092:9092"]
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092

  airflow:
    image: apache/airflow:2.9.0
    depends_on: [postgres, kafka]
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://user:password@postgres:5432/heracare
    volumes: ["./airflow/dags:/opt/airflow/dags"]
    ports: ["8080:8080"]
    command: standalone