[project]
name = "hera-care"
version = "0.1.0"
description = "Medical advisory system for PCOS detection"
requires-python = ">=3.13"
dependencies = [
    "python-dateutil>=2.9.0.post0",
]

[project.scripts]
hera-cli = "app.cli:cli"

[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["app", "ml"]

[tool.setuptools.package-data]
ml = ["data/**/*", "models/**/*"]
